CREATE VIEW ADDRESS_COMBINED_VIEW

AS

SELECT
AD.ADDRESS_DETAIL_PID as ADDRESS_DETAIL_PID,
AD.STREET_LOCALITY_PID as STREET_LOCALITY_PID,
AD.LOCALITY_PID as LOCALITY_PID,
AD.BUILDING_NAME as BUILDING_NAME,

IFNULL(AD.LOT_NUMBER_PREFIX, '')||IFNULL(AD.LOT_NUMBER, '')||IFNULL(AD.LOT_NUMBER_SUFFIX, '') as LOT_NUMBER,

FTA.NAME as FLAT_TYPE,
IFNULL(AD.FLAT_NUMBER_PREFIX, '')||IFNULL(AD.FLAT_NUMBER, '')||IFNULL(AD.FLAT_NUMBER_SUFFIX, '') as FLAT_NUMBER,

LTA.NAME as LEVEL_TYPE,
IFNULL(AD.LEVEL_NUMBER_PREFIX, '')||IFNULL(AD.LEVEL_NUMBER, '')||IFNULL(AD.LEVEL_NUMBER_SUFFIX, '') as LEVEL_NUMBER,

IFNULL(AD.NUMBER_FIRST_PREFIX, '')||IFNULL(AD.NUMBER_FIRST, '')||IFNULL(AD.NUMBER_FIRST_SUFFIX, '') as NUMBER_FIRST,
IFNULL(AD.NUMBER_LAST_PREFIX, '')||IFNULL(AD.NUMBER_LAST, '')||IFNULL(AD.NUMBER_LAST_SUFFIX, '') as NUMBER_LAST,

SL.STREET_CLASS_CODE as STREET_CLASS_CODE,
SCA.NAME as STREET_CLASS_TYPE,
TRIM(IFNULL(SL.STREET_NAME, '')||' '||IFNULL(SL.STREET_TYPE_CODE, '')) as STREET,
SL.STREET_SUFFIX_CODE as STREET_SUFFIX_CODE,
SSA.NAME as STREET_SUFFIX_TYPE,

L.LOCALITY_NAME as LOCALITY_NAME,

ST.STATE_ABBREVIATION as STATE_ABBREVIATION,

AD.POSTCODE as POSTCODE,

ADG.LATITUDE as LATITUDE,
ADG.LONGITUDE as LONGITUDE,
GTA.NAME as GEOCODE_TYPE,

AD.CONFIDENCE as CONFIDENCE,

AD.ALIAS_PRINCIPAL as ALIAS_PRINCIPAL,
AD.PRIMARY_SECONDARY as PRIMARY_SECONDARY,

AD.LEGAL_PARCEL_ID as LEGAL_PARCEL_ID,

AD.DATE_CREATED as DATE_CREATED,
AD.DATE_LAST_MODIFIED as DATE_LAST_MODIFIED

FROM

ADDRESS_DETAIL AD 
LEFT JOIN FLAT_TYPE_AUT FTA ON AD.FLAT_TYPE_CODE=FTA.CODE
LEFT JOIN LEVEL_TYPE_AUT LTA ON AD.LEVEL_TYPE_CODE=LTA.CODE
JOIN STREET_LOCALITY SL ON AD.STREET_LOCALITY_PID=SL.STREET_LOCALITY_PID
LEFT JOIN STREET_SUFFIX_AUT SSA ON SL.STREET_SUFFIX_CODE=SSA.CODE
LEFT JOIN STREET_CLASS_AUT SCA ON SL.STREET_CLASS_CODE=SCA.CODE 
LEFT JOIN STREET_TYPE_AUT STA ON SL.STREET_TYPE_CODE=STA.CODE
JOIN LOCALITY L ON AD.LOCALITY_PID = L.LOCALITY_PID
JOIN ADDRESS_DEFAULT_GEOCODE ADG ON AD.ADDRESS_DETAIL_PID=ADG.ADDRESS_DETAIL_PID
LEFT JOIN GEOCODE_TYPE_AUT GTA ON ADG.GEOCODE_TYPE_CODE=GTA.CODE
LEFT JOIN GEOCODED_LEVEL_TYPE_AUT GLTA ON AD.LEVEL_GEOCODED_CODE=GLTA.CODE
JOIN STATE ST ON L.STATE_PID=ST.STATE_PID

WHERE 
AD.CONFIDENCE > -1;